site_name: hadal
theme:
  name: material
  features:
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true

plugins:
  - search
  - section-index
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths:
            - hadal
          options:
            docstring_style: google
            allow_inspection: true
            show_bases: true
            show_source: true
            heading_level: 3
            show_root_heading: true
            show_root_full_path: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_section_style: list
            annotations_path: source
            separate_signature: true
            line_length: 80
            show_signature: true
            show_signature_annotations: true
            members_order: source
            filters: []

copyright: |
  &copy; 2023 <a href="https://github.com/rggdmonk"  target="_blank" rel="noopener">Pavel Stepachev</a>

nav:
  - Home:
      - index.md
      - installation.md
  - Parallel Sentences:
      - parallel_text.md
      - parallel_sentence_mining/margin_based.md
  - API: reference/

extra_css:
  - stylesheets/extra.css
