name: Build and Deploy MkDocs Material to GitHub Pages
name: Deploy documentation to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install \
          mkdocs-material \
          mkdocs-gen-files \
          mkdocs-literate-nav \
          mkdocs-section-index \
          mkdocstrings \
          mkdocstrings-python \
          pymdown-extensions \
      - run: mkdocs gh-deploy --force
